# TODO:
# - [ ] use default species across all time and space: sardine (since motivated creation of CalCOFI; see https://en.wikipedia.org/wiki/CalCOFI)

# Load libraries
# remotes::install_github("bbest/mapgl@fix-compare-widget-parity", force=T) # https://github.com/walkerke/mapgl/pull/187
# remotes::install_github("calcofi/calcofi4r", force = T)
#   NOTE: the reproducible-download bundle (functions.R::build_download_bundle)
#   needs calcofi4r >= 1.2.0 for cc_match_bio_env(); build_download_bundle()
#   errors clearly if an older version is installed.
# remotes::install_github("bbest/mapgl@feat/add-h3t-source", force=T)       # https://github.com/walkerke/mapgl/pull/199
#
# `library()`, NOT `librarian::shelf()` — a deliberate exception to the
# convention in ../../CLAUDE.md.
#
# NOT for speed: measured interleaved over three runs each, the two are the
# same to within run-to-run noise (3.6-6.5 s either way). The reason is that a
# served app should not be installing packages at runtime — shelf() will fetch
# and install a missing dependency on first request, which turns a deploy
# mistake into a slow, silent, half-working app instead of a startup failure,
# and does it as the `shiny` user against whatever library path it happens to
# have write access to.
#
# The trade is that a missing package is now an error. So check the whole set
# FIRST and report every missing one with the command that installs it, rather
# than dying on the first `library()` and making a deploy a game of
# whack-a-mole — two of these are GitHub-only, one of them a fork, so the right
# command is not the same for all of them.
PKGS <- c(
  "bslib", "bsicons", "calcofi4r", "conductor", "data.tree", "DBI", "dplyr",
  "DT", "duckdb", "geosphere", "ggplot2", "glue", "here", "highcharter",
  "htmltools", "htmlwidgets", "httr2", "jsonlite", "leaflet", "litedown",
  "lubridate", "mapgl", "plotly", "purrr", "readr", "sf", "shiny",
  "shinyWidgets", "stringr", "thematic", "tibble", "tidyr", "zip")

PKGS_GITHUB <- c(
  calcofi4r = "calcofi/calcofi4r",
  # the h3t tile source and the compare-widget parity fix are not upstream yet
  mapgl     = "bbest/mapgl@feat/add-h3t-source")

local({
  missing <- PKGS[!vapply(PKGS, requireNamespace, logical(1), quietly = TRUE)]
  if (length(missing) == 0) return(invisible())
  gh  <- intersect(missing, names(PKGS_GITHUB))
  cran <- setdiff(missing, gh)
  stop(
    "missing package(s): ", paste(missing, collapse = ", "), "\n",
    if (length(cran)) paste0(
      '  install.packages(c("', paste(cran, collapse = '", "'), '"))\n'),
    if (length(gh)) paste0(
      '  remotes::install_github(c("',
      paste(PKGS_GITHUB[gh], collapse = '", "'), '"))\n'),
    call. = FALSE)
})

invisible(lapply(
  PKGS, \(p) suppressPackageStartupMessages(library(p, character.only = TRUE))))

# variables ----
hex_geo <- here("data/hex.geojson")
cache_dir <- here("app/app_cache")
debug <- interactive() || nzchar(Sys.getenv("RSTUDIO")) # TRUE in console or Posit IDE
is_tour_on <- !debug # turn off while debugging

# database connection ----
# pre-built by prep_db.R with materialized bio_obs, env_obs, H3 tables
db_path <- Sys.getenv("CALCOFI_DB", here("data/calcofi_latest.duckdb"))
if (!file.exists(db_path)) {
  # fall back to most recent calcofi_*.duckdb in data/
  db_candidates <- list.files(
    here("data"),
    "^calcofi_v.*\\.duckdb$",
    full.names = TRUE
  )
  if (length(db_candidates) > 0) {
    db_path <- sort(db_candidates, decreasing = TRUE)[1]
  } else {
    stop("No database found. Run prep_db.R first.")
  }
}
message("Using database: ", db_path)
drv <- duckdb(dbdir = db_path, read_only = TRUE)
con <- dbConnect(drv)
# The server runs Shiny apps as the shiny user, which has its own home
# at /home/shiny/. Extensions install to ~/.local/share/R/duckdb/extensions/
#   which is per-user.
dbExecute(con, "INSTALL h3 FROM community; LOAD h3;")
dbExecute(con, "INSTALL spatial; LOAD spatial;")
# dbListTables(con) |> sort()

# hexagons (pre-generated by prep_db.R) are NOT read here.
# `hex_geo` is 153 MB / 434,218 polygons and cost ~5.6 s + ~370 MB of RSS in
# every session, to serve two functions that only run on the classic
# (non-h3t) path. functions.R::get_sf_hex() reads it on first use instead.

# spatial layers registry ----
d_spatial_layers <- read_csv(
  here("../workflows/metadata/spatial_layers.csv"),
  show_col_types = FALSE
)
# pmtiles_base_url <- "https://file.calcofi.io/_spatial"
pmtiles_base_url <- "https://storage.googleapis.com/calcofi-files-public/_spatial"

# gcloud storage buckets describe gs://calcofi-files-public --format="/Users/bbest/Github/CalCOFI/db-viz-hex/data/_cors_file.json"
# cd ~/Github/CalCOFI/db-viz-hex/data
# gcloud storage buckets update gs://calcofi-files-public --cors-file=_cors_file.json

# spatial summary layers ----
# Which boundary layers the map can summarize WITHIN (as opposed to the H3
# hexagons). Driven off `sample_spatial` — the sample-grain point-in-polygon
# membership table prep_db.R materializes — so a layer only appears if
# observations actually fall in it. That also keeps three broken layers out of
# the picker on its own: the release ships National Marine Sanctuaries, CA
# Watersheds (HUC8) and Ocean Disposal Sites as GEOMETRYCOLLECTION EMPTY (an
# ingest_spatial.qmd bug), so they have no memberships to summarize and no
# geometry to draw.
# Simplification for the polygon geometry sent to the browser. 0.0001 degrees is
# ~11 m — finer than the ~65 m edge of an H3 res-10 cell, the finest bin the hex
# view ever draws — so a boundary is never the coarser of the two things on
# screen. Costs 2.8 MB of WKT on the worst layer (CDFW Regions) against 10.8 MB
# unsimplified, and under 1 MB on most.
POLY_SIMPLIFY_DEG <- 0.0001

d_summary_layers <- dbGetQuery(
  con,
  "SELECT layer,
          COUNT(DISTINCT spatial_key) AS n_polygons,
          COUNT(DISTINCT sample_key)  AS n_samples
     FROM sample_spatial
    GROUP BY 1") |>
  inner_join(
    d_spatial_layers |>
      filter(geom_type == "polygon") |>
      select(layer, group),
    by = "layer") |>
  arrange(group, desc(n_samples))

# "Summarize Within" choices: hexagons, then one optgroup per registry group.
# SINGLE-select on purpose — layers overlap (a station is inside a county AND an
# ecoregion AND an MPA, all true at once), so letting several be summarized
# together would count the same observation more than once.
agg_unit_choices <- c(
  list("Hexagons (H3)" = "hex"),
  split(d_summary_layers$layer, d_summary_layers$group) |>
    lapply(\(x) setNames(as.list(x), x)))

message("summarizable spatial layers: ", nrow(d_summary_layers))

# load functions ----
source(here("app/functions.R"))
source(here("app/functions_h3t.R"))

# usage logging ----
# GA4 + a batched beacon to the usage-log Sheet, both driven from the BROWSER
# (calcofi4r::cc_ga_head() in ui.R; calcofi4r::cc_track*() in server.R) so no
# reactive ever waits on a network request — see analytics/README.md.
# .Renviron not working on the server, so setting manually. Empty => the Sheet
# leg is a silent no-op and only GA4 receives events — which is what a local or
# IDE session gets, so test clicks don't land in the production log Sheet (set
# CALCOFI_LOG_URL yourself to exercise it).
if (!debug && !nzchar(Sys.getenv("CALCOFI_LOG_URL")))
  Sys.setenv(CALCOFI_LOG_URL = "https://script.google.com/macros/s/AKfycbz95X4Dlrc1ppd0TeT-5w4I7inkfXxngqZsxTvE_gcrPBv3rPK3lyJOcAJcfAaSjiqF/exec")

# stamped on every logged event, so a Sheet row can be tied back to the exact
# code that produced it: the deployed commit, falling back to the release the
# app's DuckDB was built from.
APP_VERSION <- local({
  # `-c safe.directory=*` is required, not optional: shiny-server runs the app
  # as `shiny` while the deployed clone is owned by the user who pulled it, and
  # git refuses to read a repo it considers "dubious ownership" — which silently
  # dropped every logged app_version to the release-tag fallback ("latest").
  sha <- tryCatch(
    suppressWarnings(system2(
      "git", c("-c", "safe.directory=*", "-C", shQuote(here()),
               "rev-parse", "--short", "HEAD"),
      stdout = TRUE, stderr = FALSE))[1],
    error = function(e) NA_character_)
  if (!is.null(sha) && !is.na(sha) && nzchar(sha)) sha
  else sub("^calcofi_(.*)\\.duckdb$", "\\1", basename(db_path))
})
message("APP_VERSION: ", APP_VERSION)

# .Renviron not working, so setting manually.
# H3T_USE ON: the h3t tile service (api-h3t-py) is migrated to the consolidated
# core schema — it reads the v2026.07.15 db (bio_obs/env_obs carry hex_id) and
# serves tiles from h3_cell_to_parent(hex_id, {{res}}) (functions_h3t.R). If the
# service regresses, set FALSE to fall back to local hexagon rendering.

# H3T_RELEASE is DERIVED from the database this app opens, never hardcoded.
#
# It is the cache-buster baked into every tile URL, and the h3t API reads the
# SAME `calcofi_latest.duckdb` symlink that `db_path` above resolves — the one
# prep_db.R advances on every release. Hardcoded, it drifted: the symlink reached
# v2026.08.04 while this still said v2026.07.16, so Varnish (which keys on URL)
# kept serving tiles computed from the OLD release under an unchanged URL.
# Nothing errored, no request failed — the map was just quietly out of date.
#
# Deriving it from the symlink target means the tag and the data cannot disagree,
# and a release needs no edit here at all. CALCOFI_H3T_RELEASE still overrides,
# for pinning during an investigation.
h3t_release_of <- function(path) {
  tgt <- Sys.readlink(path)
  if (!nzchar(tgt)) tgt <- path          # not a symlink: read the filename itself
  m <- regmatches(basename(tgt),
                  regexpr("v[0-9]{4}\\.[0-9]{2}\\.[0-9]{2}", basename(tgt)))
  if (length(m)) m else ""
}
# The frozen release every number in this app comes from. Shown in the header
# (ui.R) and reused below as the tile cache-buster.
#
# It is read off the DuckDB THIS app opened, which is the honest label for the
# tables, plots and downloads. Note it can disagree with the h3t tile service on
# a dev machine: the service always opens its own `calcofi_latest.duckdb` and
# ignores the `release=` it is handed (that param is only a Varnish cache key),
# so a local DuckDB lagging the server means the header says one release while
# the map draws another. On the server the two are the same symlink, so they
# cannot drift there.
DB_RELEASE  <- h3t_release_of(db_path)
h3t_release <- Sys.getenv("CALCOFI_H3T_RELEASE", DB_RELEASE)
if (!nzchar(h3t_release))
  warning("could not derive H3T_RELEASE from ", db_path,
          " — tile URLs will not be release-tagged, so Varnish may serve stale tiles")

Sys.setenv(
  H3T_USE      = TRUE,
  H3T_BASE_URL = "https://h3t.calcofi.io/h3t",
  H3T_RELEASE  = h3t_release)

# h3t feature flag — when TRUE, the app skips the 10-resolution sf preload and
# reads hex data on-demand from the h3t tile API (see api-h3t/). default off.
USE_H3T <- isTRUE(as.logical(Sys.getenv("H3T_USE", "FALSE")))
H3T_RELEASE <- Sys.getenv("H3T_RELEASE", "")  # baked into tile URLs

message("USE_H3T: ", USE_H3T)
message("H3T_RELEASE: ", H3T_RELEASE)

# taxa, and which datasets they come from ----
# `species` carries every taxon in the release; `bio_obs` says which of them a
# given dataset actually observed. Both are needed: the picker still lists
# everything by default, but the Dataset filter narrows it to what that dataset
# holds. 80 of 993 taxa appear in MORE than one dataset (Appendicularia is in
# both zoodb and zooscan), so this is a filter, not a partition.
# Joined on taxon_key and NOT filtered to authority WoRMS. Two reasons, and the
# second is load-bearing: seabirds key `itis:`, so a WoRMS-only join returned a
# NULL taxonRank for every one of them; and `resolve_sp_ids()` must rebuild this
# EXACT label to match the user's selection. If one side emits
# "Common Murre (Uria aalge)" and the other "Common Murre (species: Uria aalge)",
# the selection resolves to zero rows with no error — which is precisely the
# divergence documented in taxa_tree_builder(). Change these two together.
d_sp <- tbl(con, "species") |>
  left_join(
    tbl(con, "taxon"),
    by = join_by(taxon_key == taxonID)
  ) |>
  mutate(
    rank_part = ifelse(
      is.na(taxonRank) | taxonRank == "",
      "",
      paste0(tolower(taxonRank), ": ")),
    name_part = ifelse(
      is.na(common_name) | common_name == "",
      "",
      paste0(common_name, " ")),
    name = paste0(name_part, "(", rank_part, scientific_name, ")")
  ) |>
  select(scientific_name, name) |>
  collect() |>
  distinct(scientific_name, .keep_all = TRUE)

sp_names <- sort(d_sp$name)

# Which dataset(s) observed each taxon, keyed on scientific_name and NOT on
# worms_id. The original reason was that seabirds and marine mammals resolve to
# ITIS, so `farallon_bird-mammal` carried a NULL worms_id on 59,858 of its 64,956
# rows and a worms_id join dropped 92% of the dataset without a word. Release
# v2026.08.06 gives every one of those taxa a worms_id, so that specific hazard
# is gone — but scientific_name (or taxon_key) remains the right key here,
# because it does not depend on which authority happens to own a taxon.
d_taxa_ds <- dbGetQuery(
  con,
  "SELECT DISTINCT dataset_key, scientific_name FROM bio_obs
    WHERE scientific_name IS NOT NULL")

bio_date_rng <- tbl(con, "bio_obs") |>
  summarize(
    date_min = min(time_start, na.rm = TRUE) |> as.Date(),
    date_max = max(time_start, na.rm = TRUE) |> as.Date()
  ) |>
  collect() |>
  as.vector()

env_date_rng <- tbl(con, "env_obs") |>
  summarize(
    date_min = min(datetime_utc, na.rm = TRUE) |> as.Date(),
    date_max = max(datetime_utc, na.rm = TRUE) |> as.Date()
  ) |>
  collect() |>
  as.vector()

min_max_date <- c(
  min(bio_date_rng[[1]], env_date_rng[[1]]),
  max(bio_date_rng[[2]], env_date_rng[[2]])
)

# global constants ----
default_sp_name <- "Pacific sardine (pilchard) (species: Sardinops sagax)"
default_max_hours_diff <- 6
default_max_meters_diff <- 2000

ts_res_choices <- list(
  "Year" = "year",
  "Quarter" = "quarter",
  "Year, Quarter" = "year_quarter"
)

# environmental variables + contributing datasets ----
# Was a hardcoded list of 15. `env_obs` holds 78 measurement types across 5
# datasets, so that list exposed 19% of the data and silently spanned two
# sources (the nutrients are Bottle; pressure/par/ph are CTD Cast).
#
# Every env measurement_type belongs to EXACTLY ONE dataset (verified: 0 of 78
# span more than one), which is what makes grouping the picker by dataset work:
# each entry appears once, and the group heading disambiguates the families that
# collide on a pretty label — `nitrite` (Bottle) and `btl_nitrite` (bottle
# sample drawn on a CTD cast) are otherwise both "Nitrite (umol/L)".
DATASET_LABELS <- c(
  "calcofi_bottle"                 = "CalCOFI: Bottle",
  "calcofi_ctd-cast"               = "CalCOFI: CTD Cast",
  "calcofi_mets"                   = "CalCOFI: METS (underway)",
  "calcofi_dic"                    = "CalCOFI: DIC (carbon)",
  "cce-lter_picoplankton-bacteria" = "CCE-LTER: Picoplankton & bacteria",
  "swfsc_ichthyo"                  = "SWFSC: Ichthyoplankton",
  "swfsc_cufes"                    = "SWFSC: CUFES (egg pump)",
  "calcofi_phytoplankton"          = "CalCOFI: Phytoplankton",
  "cce-lter_zooscan"               = "CCE-LTER: ZooScan",
  "cce-lter_euphausiids"           = "CCE-LTER: Euphausiids",
  "cce-lter_zoodb"                 = "CCE-LTER: ZooDB",
  "farallon_bird-mammal"           = "Farallon: Seabirds & mammals",
  "calcofi_phyllosoma"             = "CalCOFI: Phyllosoma",
  "sio_mesopelagic-fish"           = "SIO: Mesopelagic fish")

# falls back to the raw key rather than NA, so a newly ingested dataset shows up
# looking unpolished instead of vanishing (cf. the provider.csv lesson)
dataset_label <- function(key) {
  lbl <- unname(DATASET_LABELS[key])
  ifelse(is.na(lbl), key, lbl)
}

# the registry stores units ASCII-safe ("umol/L", "degC", "kg/m3"); render them
# the way the old hand-written list did, so the picker reads like a data sheet
pretty_units <- function(u) {
  u |>
    str_replace_all("\\bumol\\b", "\u00b5mol") |>
    str_replace_all("\\bug\\b",   "\u00b5g") |>
    str_replace_all("\\buE\\b",   "\u00b5E") |>
    str_replace_all("\\bdeg_?C\\b", "\u00b0C") |>
    str_replace_all("m3", "m\u00b3") |>
    str_replace_all("m2", "m\u00b2")
}

d_env_vars <- dbGetQuery(
  con,
  "SELECT dataset_key, measurement_type, ANY_VALUE(units) AS units, COUNT(*) AS n_obs
     FROM env_obs GROUP BY 1, 2") |>
  left_join(
    tbl(con, "measurement_type") |>
      select(measurement_type, description) |>
      collect(),
    by = "measurement_type") |>
  mutate(
    # the registry's `description` IS the short human name ("Bottle nitrite",
    # "Water temperature (QC'd)"); anything after a ";" is a caveat, not a name
    var_name = str_squish(str_remove(description, ";.*$")),
    var_name = ifelse(
      is.na(var_name) | var_name == "",
      str_to_sentence(str_replace_all(measurement_type, "_", " ")),
      var_name),
    label = ifelse(
      is.na(units) | units == "" | units == "NA",
      var_name, paste0(var_name, " (", pretty_units(units), ")"))) |>
  arrange(dataset_key, var_name)

# a label must be unique WITHIN its dataset or the two entries are
# indistinguishable in the dropdown; disambiguate with the slug if it happens
d_env_vars <- d_env_vars |>
  group_by(dataset_key, label) |>
  mutate(label = if (n() > 1) paste0(label, " [", measurement_type, "]") else label) |>
  ungroup()

# Headline variables: the ones people actually plot. Everything else — the
# instrument channels (isus_v, spar, transmissometer), the pre-QC `r_*` reports,
# and the averaged/corrected/per-replicate variants — stays behind "Show all",
# which keeps the common path short without hiding anything.
ENV_HEADLINE_TYPES <- c(
  # calcofi_bottle
  "temperature", "salinity", "oxygen_umol_kg", "oxygen_ml_l", "oxygen_saturation",
  "phosphate", "silicate", "nitrate", "nitrite", "ammonia",
  "chlorophyll_a", "phaeopigment", "sigma_theta", "c14_mean",
  # calcofi_ctd-cast
  "temperature_ave", "salinity_ave_corr", "oxygen_umol_kg_ave_sta_corr",
  "pressure", "par", "ph", "dynamic_height", "fluorescence_v",
  # calcofi_dic
  "dic", "alkalinity",
  # calcofi_mets
  "sst_c", "sss_psu", "wind_speed_ms", "air_temp_c", "chl_fluor",
  # cce-lter_picoplankton-bacteria
  "prochlorococcus", "synechococcus", "het_bacteria", "picoeukaryotes")

# A dataset with no headline variable would appear in the Dataset filter with an
# empty Variable list — a dead end that looks like a bug. Fail loudly at startup
# instead, so adding a dataset forces a decision about what it leads with.
local({
  missing <- setdiff(
    unique(d_env_vars$dataset_key),
    unique(d_env_vars$dataset_key[d_env_vars$measurement_type %in% ENV_HEADLINE_TYPES]))
  if (length(missing) > 0)
    stop("no headline env variable for: ", paste(missing, collapse = ", "),
         " — add one to ENV_HEADLINE_TYPES in global.R")
})

# Datasets are listed ALPHABETICALLY by display name, not by volume: these are
# pick-lists, so a dataset should sit where its name puts it rather than move
# as the counts change between releases. The order set here drives both the
# checkbox groups and the optgroup order in env_var_choices().
#
# Sorted on the LOWERCASED name. dplyr's arrange() uses the C locale, which
# orders every uppercase letter before every lowercase one — that puts
# "CCE-LTER" ahead of "CalCOFI", which is not what alphabetical means to a
# reader. Lowercasing first is also locale-independent, so the order does not
# depend on the LC_COLLATE of whatever machine serves the app.
d_env_datasets <- d_env_vars |>
  group_by(dataset_key) |>
  summarize(n_obs = sum(n_obs), n_types = n(), .groups = "drop") |>
  mutate(ds_name = dataset_label(dataset_key)) |>
  arrange(tolower(ds_name)) |>
  mutate(label = sprintf("%s — %s obs, %d variables",
                         ds_name, format(n_obs, big.mark = ","), n_types))

d_bio_datasets <- dbGetQuery(
  con,
  "SELECT dataset_key, COUNT(*) AS n_obs,
          COUNT(DISTINCT scientific_name) AS n_taxa
     FROM bio_obs GROUP BY 1") |>
  mutate(ds_name = dataset_label(dataset_key)) |>
  arrange(tolower(ds_name)) |>
  mutate(label = sprintf("%s — %s obs, %d taxa",
                         ds_name, format(n_obs, big.mark = ","), n_taxa))

#' Grouped choices for the Environmental Variable picker
#'
#' @param datasets character vector of dataset_key to include (NULL = all)
#' @param show_all include every measurement type, not just the headline set
#' @return named list of named lists, one group per dataset (selectInput optgroups)
env_var_choices <- function(datasets = NULL, show_all = FALSE) {
  d <- d_env_vars
  if (!is.null(datasets) && length(datasets) > 0)
    d <- d[d$dataset_key %in% datasets, ]
  if (!isTRUE(show_all))
    d <- d[d$measurement_type %in% ENV_HEADLINE_TYPES, ]
  if (nrow(d) == 0) return(list())

  # keep dataset groups in the same order as the Dataset checkboxes
  ds <- d_env_datasets$dataset_key[d_env_datasets$dataset_key %in% d$dataset_key]
  out <- lapply(ds, function(k) {
    x <- d[d$dataset_key == k, ]
    setNames(as.list(x$measurement_type), x$label)
  })
  setNames(out, dataset_label(ds))
}

#' Display label for one measurement type, e.g. "Nitrite concentration (umol/L)"
#' Replaces `names(which(env_var_choices == mt))`, which cannot survive two
#' types sharing a label.
env_var_label <- function(mt) {
  i <- match(mt, d_env_vars$measurement_type)
  ifelse(is.na(i), mt, d_env_vars$label[i])
}

#' Taxa names for the picker, optionally restricted to the datasets that hold them
sp_names_for <- function(datasets = NULL) {
  if (is.null(datasets) || length(datasets) == 0) return(sp_names)
  sci <- d_taxa_ds$scientific_name[d_taxa_ds$dataset_key %in% datasets]
  sort(d_sp$name[d_sp$scientific_name %in% sci])
}

env_stat_choices <- list(
  "Avg." = "mean",
  "Max" = "max",
  "Min" = "min",
  "Std. Dev." = "sd"
)

# mapping variables ----
min_res <- 1
max_res <- 10
res_range <- min_res:max_res
zoom_breaks <- seq(1, 13, length.out = length(res_range) + 1)
zoom_breaks[1] <- 0
zoom_breaks[length(zoom_breaks)] <- 22

# tour ----
tour <- Conductor$new(
  exitOnEsc = T,
  keyboardNavigation = T,
  # show an "X" close icon on every step so the welcome/tour can be dismissed
  # without a keyboard (esc is unavailable on phones)
  defaultStepOptions = list(
    cancelIcon = list(enabled = TRUE, label = "Close")
  )
)$step(
  title = "Welcome",
  text = "The app is initializing with a map comparing Pacific sardine larvae
    and temperature collected on CalCOFI cruises since 1949.<br><br>
    (To exit the tour, tap the &times; or press esc)",
  buttons = list(
    list(
      action = "next",
      text = "Next"
    )
  )
)$step(
  el = "#sel_data",
  title = "Select Filters",
  text = "You can change the species and environmental selection here, along with
    temporal and spatial constraints.",
  buttons = list(
    list(
      action = "back",
      text = "Back"
    ),
    list(
      action = "next",
      text = "Done"
    )
  )
)

# cleanup on exit ----
onStop(function() {
  dbDisconnect(con, shutdown = TRUE)
})
