# TODO:
# - [ ] use default species across all time and space: sardine (since motivated creation of CalCOFI; see https://en.wikipedia.org/wiki/CalCOFI)

# Install librarian if needed
if (!requireNamespace("librarian", quietly = TRUE)) {
  install.packages("librarian")
}

# Load libraries
# remotes::install_github("bbest/mapgl@fix-compare-widget-parity", force=T) # https://github.com/walkerke/mapgl/pull/187
# remotes::install_github("calcofi/calcofi4r", force = T)
#   NOTE: the reproducible-download bundle (functions.R::build_download_bundle)
#   needs calcofi4r >= 1.2.0 for cc_match_bio_env(); build_download_bundle()
#   errors clearly if an older version is installed.
# remotes::install_github("bbest/mapgl@feat/add-h3t-source", force=T)       # https://github.com/walkerke/mapgl/pull/199
librarian::shelf(
  bslib,
  bsicons,
  calcofi / calcofi4r,
  conductor,
  data.tree,
  DBI,
  dplyr,
  DT,
  duckdb,
  geosphere,
  ggplot2,
  glue,
  here,
  highcharter,
  htmltools,
  htmlwidgets,
  httr2,
  jsonlite,
  leaflet,
  litedown,
  lubridate,
  mapgl,
  plotly,
  purrr,
  readr,
  sf,
  shiny,
  shinyWidgets,
  stringr,
  thematic,
  tibble,
  tidyr,
  zip,
  quiet = TRUE
)

# variables ----
hex_geo <- here("data/hex.geojson")
cache_dir <- here("app/app_cache")
debug <- interactive() || nzchar(Sys.getenv("RSTUDIO")) # TRUE in console or Posit IDE
is_tour_on <- !debug # turn off while debugging

# database connection ----
# pre-built by prep_db.R with materialized bio_obs, env_obs, H3 tables
db_path <- Sys.getenv("CALCOFI_DB", here("data/calcofi_latest.duckdb"))
if (!file.exists(db_path)) {
  # fall back to most recent calcofi_*.duckdb in data/
  db_candidates <- list.files(
    here("data"),
    "^calcofi_v.*\\.duckdb$",
    full.names = TRUE
  )
  if (length(db_candidates) > 0) {
    db_path <- sort(db_candidates, decreasing = TRUE)[1]
  } else {
    stop("No database found. Run prep_db.R first.")
  }
}
message("Using database: ", db_path)
drv <- duckdb(dbdir = db_path, read_only = TRUE)
con <- dbConnect(drv)
# The server runs Shiny apps as the shiny user, which has its own home
# at /home/shiny/. Extensions install to ~/.local/share/R/duckdb/extensions/
#   which is per-user.
dbExecute(con, "INSTALL h3 FROM community; LOAD h3;")
dbExecute(con, "INSTALL spatial; LOAD spatial;")
# dbListTables(con) |> sort()

# load hexagons (pre-generated by prep_db.R)
sf_hex <- st_read(hex_geo, quiet = TRUE)

# spatial layers registry ----
d_spatial_layers <- read_csv(
  here("../workflows/metadata/spatial_layers.csv"),
  show_col_types = FALSE
)
# pmtiles_base_url <- "https://file.calcofi.io/_spatial"
pmtiles_base_url <- "https://storage.googleapis.com/calcofi-files-public/_spatial"

# gcloud storage buckets describe gs://calcofi-files-public --format="/Users/bbest/Github/CalCOFI/db-viz-hex/data/_cors_file.json"
# cd ~/Github/CalCOFI/db-viz-hex/data
# gcloud storage buckets update gs://calcofi-files-public --cors-file=_cors_file.json

# spatial summary layers ----
# Which boundary layers the map can summarize WITHIN (as opposed to the H3
# hexagons). Driven off `sample_spatial` — the sample-grain point-in-polygon
# membership table prep_db.R materializes — so a layer only appears if
# observations actually fall in it. That also keeps three broken layers out of
# the picker on its own: the release ships National Marine Sanctuaries, CA
# Watersheds (HUC8) and Ocean Disposal Sites as GEOMETRYCOLLECTION EMPTY (an
# ingest_spatial.qmd bug), so they have no memberships to summarize and no
# geometry to draw.
# Simplification for the polygon geometry sent to the browser. 0.0001 degrees is
# ~11 m — finer than the ~65 m edge of an H3 res-10 cell, the finest bin the hex
# view ever draws — so a boundary is never the coarser of the two things on
# screen. Costs 2.8 MB of WKT on the worst layer (CDFW Regions) against 10.8 MB
# unsimplified, and under 1 MB on most.
POLY_SIMPLIFY_DEG <- 0.0001

d_summary_layers <- dbGetQuery(
  con,
  "SELECT layer,
          COUNT(DISTINCT spatial_key) AS n_polygons,
          COUNT(DISTINCT sample_key)  AS n_samples
     FROM sample_spatial
    GROUP BY 1") |>
  inner_join(
    d_spatial_layers |>
      filter(geom_type == "polygon") |>
      select(layer, group),
    by = "layer") |>
  arrange(group, desc(n_samples))

# "Summarize Within" choices: hexagons, then one optgroup per registry group.
# SINGLE-select on purpose — layers overlap (a station is inside a county AND an
# ecoregion AND an MPA, all true at once), so letting several be summarized
# together would count the same observation more than once.
agg_unit_choices <- c(
  list("Hexagons (H3)" = "hex"),
  split(d_summary_layers$layer, d_summary_layers$group) |>
    lapply(\(x) setNames(as.list(x), x)))

message("summarizable spatial layers: ", nrow(d_summary_layers))

# load functions ----
source(here("app/functions.R"))
source(here("app/functions_h3t.R"))

# usage logging ----
# GA4 + a batched beacon to the usage-log Sheet, both driven from the BROWSER
# (calcofi4r::cc_ga_head() in ui.R; calcofi4r::cc_track*() in server.R) so no
# reactive ever waits on a network request — see analytics/README.md.
# .Renviron not working on the server, so setting manually. Empty => the Sheet
# leg is a silent no-op and only GA4 receives events — which is what a local or
# IDE session gets, so test clicks don't land in the production log Sheet (set
# CALCOFI_LOG_URL yourself to exercise it).
if (!debug && !nzchar(Sys.getenv("CALCOFI_LOG_URL")))
  Sys.setenv(CALCOFI_LOG_URL = "https://script.google.com/macros/s/AKfycbz95X4Dlrc1ppd0TeT-5w4I7inkfXxngqZsxTvE_gcrPBv3rPK3lyJOcAJcfAaSjiqF/exec")

# stamped on every logged event, so a Sheet row can be tied back to the exact
# code that produced it: the deployed commit, falling back to the release the
# app's DuckDB was built from.
APP_VERSION <- local({
  # `-c safe.directory=*` is required, not optional: shiny-server runs the app
  # as `shiny` while the deployed clone is owned by the user who pulled it, and
  # git refuses to read a repo it considers "dubious ownership" — which silently
  # dropped every logged app_version to the release-tag fallback ("latest").
  sha <- tryCatch(
    suppressWarnings(system2(
      "git", c("-c", "safe.directory=*", "-C", shQuote(here()),
               "rev-parse", "--short", "HEAD"),
      stdout = TRUE, stderr = FALSE))[1],
    error = function(e) NA_character_)
  if (!is.null(sha) && !is.na(sha) && nzchar(sha)) sha
  else sub("^calcofi_(.*)\\.duckdb$", "\\1", basename(db_path))
})
message("APP_VERSION: ", APP_VERSION)

# .Renviron not working, so setting manually.
# H3T_USE ON: the h3t tile service (api-h3t-py) is migrated to the consolidated
# core schema — it reads the v2026.07.15 db (bio_obs/env_obs carry hex_id) and
# serves tiles from h3_cell_to_parent(hex_id, {{res}}) (functions_h3t.R). If the
# service regresses, set FALSE to fall back to local hexagon rendering.
Sys.setenv(
  H3T_USE      = TRUE,
  H3T_BASE_URL = "https://h3t.calcofi.io/h3t",
  H3T_RELEASE  = "v2026.07.16")

# h3t feature flag — when TRUE, the app skips the 10-resolution sf preload and
# reads hex data on-demand from the h3t tile API (see api-h3t/). default off.
USE_H3T <- isTRUE(as.logical(Sys.getenv("H3T_USE", "FALSE")))
H3T_RELEASE <- Sys.getenv("H3T_RELEASE", "")  # baked into tile URLs

message("USE_H3T: ", USE_H3T)
message("H3T_RELEASE: ", H3T_RELEASE)

# extract species names and date range ----
# all species (ichthyo + invert) are in the species table with WoRMS taxonomy
sp_names <- tbl(con, "species") |>
  left_join(
    tbl(con, "taxon") |>
      filter(authority == "WoRMS"),
    by = join_by(worms_id == taxonID)
  ) |>
  mutate(
    rank_part = ifelse(
      is.na(taxonRank) | taxonRank == "",
      "",
      paste0(tolower(taxonRank), ": ")),
    name_part = ifelse(
      is.na(common_name) | common_name == "",
      "",
      paste0(common_name, " ")),
    name = paste0(name_part, "(", rank_part, scientific_name, ")")
  ) |>
  pull(name) |>
  sort()

bio_date_rng <- tbl(con, "bio_obs") |>
  summarize(
    date_min = min(time_start, na.rm = TRUE) |> as.Date(),
    date_max = max(time_start, na.rm = TRUE) |> as.Date()
  ) |>
  collect() |>
  as.vector()

env_date_rng <- tbl(con, "env_obs") |>
  summarize(
    date_min = min(datetime_utc, na.rm = TRUE) |> as.Date(),
    date_max = max(datetime_utc, na.rm = TRUE) |> as.Date()
  ) |>
  collect() |>
  as.vector()

min_max_date <- c(
  min(bio_date_rng[[1]], env_date_rng[[1]]),
  max(bio_date_rng[[2]], env_date_rng[[2]])
)

# global constants ----
default_sp_name <- "Pacific sardine (pilchard) (species: Sardinops sagax)"
default_max_hours_diff <- 6
default_max_meters_diff <- 2000

ts_res_choices <- list(
  "Year" = "year",
  "Quarter" = "quarter",
  "Year, Quarter" = "year_quarter"
)

env_var_choices <- list(
  "Temperature (\u00baC)" = "temperature",
  "Salinity (PSS-78)" = "salinity",
  "Oxygen (\u00b5mol/kg)" = "oxygen_umol_kg",
  "Phosphate (\u00b5mol/L)" = "phosphate",
  "Silicate (\u00b5mol/L)" = "silicate",
  "Nitrite (\u00b5mol/L)" = "nitrite",
  "Nitrate (\u00b5mol/L)" = "nitrate",
  "Chlorophyll-a (\u00b5g/L)" = "chlorophyll_a",
  "Phaeopigment (\u00b5g/L)" = "phaeopigment",
  "Dynamic Height (m)" = "dynamic_height",
  "Sigma-theta (kg/m\u00b3)" = "sigma_theta",
  "Pressure (dbar)" = "pressure",
  "PAR (\u00b5E/m\u00b2/s)" = "par",
  "pH" = "ph",
  "Ammonia (\u00b5mol/L)" = "ammonia"
)

env_stat_choices <- list(
  "Avg." = "mean",
  "Max" = "max",
  "Min" = "min",
  "Std. Dev." = "sd"
)

# mapping variables ----
min_res <- 1
max_res <- 10
res_range <- min_res:max_res
zoom_breaks <- seq(1, 13, length.out = length(res_range) + 1)
zoom_breaks[1] <- 0
zoom_breaks[length(zoom_breaks)] <- 22

# tour ----
tour <- Conductor$new(
  exitOnEsc = T,
  keyboardNavigation = T,
  # show an "X" close icon on every step so the welcome/tour can be dismissed
  # without a keyboard (esc is unavailable on phones)
  defaultStepOptions = list(
    cancelIcon = list(enabled = TRUE, label = "Close")
  )
)$step(
  title = "Welcome",
  text = "The app is initializing with a map comparing Pacific sardine larvae
    and temperature collected on CalCOFI cruises since 1949.<br><br>
    (To exit the tour, tap the &times; or press esc)",
  buttons = list(
    list(
      action = "next",
      text = "Next"
    )
  )
)$step(
  el = "#sel_data",
  title = "Select Filters",
  text = "You can change the species and environmental selection here, along with
    temporal and spatial constraints.",
  buttons = list(
    list(
      action = "back",
      text = "Back"
    ),
    list(
      action = "next",
      text = "Done"
    )
  )
)

# cleanup on exit ----
onStop(function() {
  dbDisconnect(con, shutdown = TRUE)
})
